### ISSUE TITLE
더 나은 방향에 대해서

### ISSUE THREAD

**Issue by bstaran** [fox9d/deliveryAPI#2]
지금 구현한 API는 현재의 제 능력으로 최선을 다해서 구현을 했지만, 첫 API 구현이기 때문에 아마 더 좋게 리팩토링할 수 있을거라고 생각이 듭니다.
하지만 어떤 부분을 더 좋게 수정할 수 있을지, 어떤 부분을 더 공부해야할 지 방향을 알고 싶어서 그것에 대한 조언을 얻고 싶습니다.
그리고 코드에 대한 리뷰도 받고 싶습니다.

**Comment by 9sanha** [comment]
프로젝트 진행하시느라 고생 많으셨습니다!
-----

일단 controller에 작성하신 ENDPOINT가 통일되지 않는 것 같아서 참고 자료 보시고 수정하시면 좋을 것 같네요 :) 아마 리스트를 반환하는 api와 차이를 두신 것 같은데요, 보편적으로 쓰는 네이밍 규칙을 기준으로 작성해주시면 협업할 때 네이밍으로 충돌나는 일은 없을거에요. 
-> [endpoint naming convention](https://betterprogramming.pub/10-best-practices-for-naming-rest-api-endpoints-442ae592a3a0)

현재는 모든 컨트롤러가 restfull하게 작성되어 있기 때문에 괜찮지만 추후에 안내 화면을 띄우는 등의 작업이 포함된다면 restController들은 클래스만 봐도 알 수 있게 네이밍 해주는 것이 좋습니다! 
> 예로 FoodController는 FoodRestController로 네이밍 하시면 됩니다 :)

----
https://github.com/fox9d/deliveryAPI/blob/3298cdeebae20ca87978bcfc0b3824e6fd626db5/src/main/java/com/innovation/deliveryapi/service/RestaurantService.java#L26-L31

위 로직같은 경우에는 else가 필요 없습니다 :)
----

계정정보 잘 숨겨두셨네요 :)
다음 과제에는 커스텀 exception을 구현해 보시는 것을 추천드립니다!

또한 service로직을 세분화 하는것도 추천드립니다.
주문을 저장하는 서비스 로직에서 주문의 유효성 검사도 같이 진행하고 있는데 이 부분을 다른 메소드로 분리하면 각 메소드의 책임이 명확해집니다!

**Comment by bstaran** [comment]
감사합니다. :)
